#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 30 21:02:22 2022

@author: oyxl
"""

class gmid:
    
    def __init__(self):
        self.name
        
    def csv_input(csv_filename)